### ISSUE TITLE
Motion crashes with segfault when camera initially not available 

### ISSUE THREAD

**Issue by codefalk** [Mr-Dave/motion#108]
Hi, 
motion crashes with segfault on Ubuntu 14.04, kernel 3.13.0-86-generic, when rtsp camera is not available at start time of motion. Crash can be reproduced. Does not crash when camera has been active and looses connection. See log:

`Jun 14 10:12:26 mx-hd motion: [2] [WRN] [NET] netcam_interrupt_rtsp: Reading picture timed out for rtsp://IP-REPLACED:555/axis-media/media.amp?streamprofile=Quality
Jun 14 10:12:26 mx-hd motion: [2] [WRN] [NET] netcam_interrupt_rtsp: Reading picture timed out for rtsp://IP-REPLACED:555/axis-media/media.amp?streamprofile=Quality
Jun 14 10:12:26 mx-hd motion: [2] [ERR] [NET] netcam_rtsp_open_context: Failed to read first image
Jun 14 10:12:26 mx-hd motion: [2] [WRN] [ALL] motion_init: Could not fetch initial image from camera Motion continues using width and height from config file(s)
Jun 14 10:12:26 mx-hd motion: [2] [NTC] [ALL] image_ring_resize: Resizing pre_capture buffer to 1 items
Jun 14 10:12:26 mx-hd motion: [2] [NTC] [STR] http_bindsock: motion-stream testing : IPV4 addr: 127.0.0.1 port: 10136
Jun 14 10:12:26 mx-hd motion: [2] [NTC] [STR] http_bindsock: motion-stream Bound : IPV4 addr: 127.0.0.1 port: 10136
Jun 14 10:12:26 mx-hd motion: [2] [NTC] [ALL] motion_init: Started motion-stream server in port 10136 auth Disabled
Jun 14 10:12:26 mx-hd motion: [2] [NTC] [ALL] motion_loop: Thread exiting
Jun 14 10:12:26 mx-hd motion: [2] [NTC] [STR] stream_stop: Closing motion-stream listen socket & active motion-stream sockets
Jun 14 10:12:26 mx-hd motion: [2] [NTC] [STR] stream_stop: Closed motion-stream listen socket & active motion-stream sockets
Jun 14 10:12:26 mx-hd kernel: [ 4991.843517] motion[20182]: segfault at 48 ip 00007f515e213111 sp 00007f51595dba40 error 4 in libc-2.19.so[7f515e15b000+1ba000]
`

**Comment by tosiara** [comment]
What version are you using?

**Comment by codefalk** [comment]
Mr. Dave's master branch.

**Comment by codefalk** [comment]
Another example:

`Jun 14 08:58:57 mx-hd motion: [0] [ERR] [ALL] main: Thread 1 - Watchdog timeout, did NOT restart graceful,killing it!
Jun 14 08:58:57 mx-hd motion: [0] [ERR] [ALL] main: Thread 2 - Watchdog timeout, did NOT restart graceful,killing it!
Jun 14 08:58:58 mx-hd motion: [0] [ERR] [ALL] main: cleaning Thread 1
Jun 14 08:58:58 mx-hd motion: [0] [NTC] [STR] stream_stop: Closing motion-stream listen socket & active motion-stream sockets
Jun 14 08:58:58 mx-hd motion: [0] [NTC] [STR] stream_stop: Closed motion-stream listen socket & active motion-stream sockets
Jun 14 08:58:58 mx-hd kernel: [  584.207905] motion[7472]: segfault at 48 ip 00007f7b998cd111 sp 00007ffe49744750 error 4 in libc-2.19.so[7f7b99815000+1ba000]`

**Comment by tosiara** [comment]
Is your camera completely offline at the start?

**Comment by codefalk** [comment]
no, it isn't. Cameras are remote cameras that have sometimes performance and bandwidth  problems. There may be a situation when they do connect, but don't deliver a data stream.

**Comment by Mr-Dave** [comment]
I am having a difficult time reproducing error.  Can you try the following to see if we can come up with a scenario that I can try to emulate.  Point to a completely IP that doesn't exist on your network.  Does it crash.  Point to a IP of a computer on the network which isn't a camera.  Does it crash?  

Also, which version of ffmpeg are you using?  Is it Libav or the real ffmpeg?  Installed from a repo or built?  


If you try ffplay rtsp://yourip:port/etc does ffplay crash?  (If you are using Libav, the command would be avplay instead of ffplay)

Finally, can you post the entire log from the start of motion until the crash?

**Comment by codefalk** [comment]
Thanks for your continuous support!
I have worked on stabilizing the cameras, therefore I need to set up a separate environment to reproduce the problem. I will also set a more detailed debug level and provide the details later.

- I compiled motion with "./configure --with-ffmpeg=/usr/include/libavutil --prefix=/usr/local/bin"
- It is Libav from repository
- Since i now occasionally see "segfault at 0 ip 00007fc03c15d0b7 sp 00007fbf806caaf0 error 4 in libavformat.so.54.20.4" it seems to be version 54.20.4
- motion is installed on a "console only" system. Therefore I am sorry to not know how to use avplay.

**Comment by codefalk** [comment]
I did a clean up of all libav related packages. Seems my installation was somewhat messed up too...
Did a reinstall of relevant packages, compiled motion and started tests. Will let you know when i can reproduce the problem.

**Comment by codefalk** [comment]
Issue still persists. 
This is what i did:
- cleaned up all libav related packed. Made sure nothing libav related is left.
- reinstalled all required libav packages from repo
- got latest master and compiled with sudo ./configure --prefix=/usr/local
- at start-up, motion crashed with error 4 in libc-2.19.so (see log motion.txt attached)
- tried to access camera from thread 22 with VLC and failed (except initial image)
- logged VLC messages (see log vlc.txt attached)
- removed thread 22 from motion.conf -> start-up successful

Looking at it with my limited programming knowledge: is it possible that this problem is caused by cleaning up memory/pointers while during initialization respective references could have not been properly set for this special case?

[motion.txt](https://github.com/Mr-Dave/motion/files/322203/motion.txt)
[vlc.txt](https://github.com/Mr-Dave/motion/files/322204/vlc.txt)

**Comment by codefalk** [comment]
An idea for reproducing the issue: 
The trick is to get the camera to a point where it is too busy to deliver images. In my case it's quite simple since the Axis 3005 cameras seem to have a very slow processor.
Configure a large amount of threads for one camera until it gets too busy. This should help to reproduce the problem.

**Comment by codefalk** [comment]
Update: The problem also occurs when the camera thread is being restarted. This leads to the same situation as at initial startup of motion.

**Comment by codefalk** [comment]
Solved: updated to kernel 3.13.0-88-generic
