### ISSUE TITLE
New Project Name

### ISSUE THREAD

**Issue by Mr-Dave** [Mr-Dave/motion#116]
IF the project moves forward with forking from the official Motion project, then the application will need a new name.  In order to maintain user recognition of the software, the word motion needs to be maintained somehow within the name.  While keeping the binary named as motion has been suggested, I feel that this will ultimately be a problem.  If the official motion project does come back to life, there could be conflicts on users machines, the interaction of libav and ffmpeg is a recent example of such a situation that caused many problems to users.   Based upon the difficulty I had with that, I have a hard time supporting doing something similar to our users.  

For the application name the following was the listed suggestions.
MotionDaemon
MotionCam
MotionLens
motion-ng
motion4
motion34(my initial thought)

I think that MotionCam would need to be ruled out since it appears to be extremely close to a Microsoft product.  The motion 4/34 I think are playing on the current version numbers which could be strange once the version numbers for the new project get added.  e.g.  Motion4_0.1 could get translated by regular users as motion version 4.0.1.  Having daemon in the name could also be confusing since it isn't required to run as a daemon.  With the list of motionlens or motion-ng I am leaning towards the -ng which I am assuming is a abbreviation for next generation.  

I invite all to comment on the binary name as well as a thoughts on what a new project would be named.  

MrDave

**Comment by DejavuDmitry** [comment]
Dave+Motion=davotion (not devotion). =)

**Comment by tosiara** [comment]
motion-ng
motion4

**Comment by jogu** [comment]
I'm happy with motionlens or motion-ng.

**Comment by ccrisan** [comment]
+1 for motion-ng.

**Comment by jeff-h** [comment]
In some circles, ng is a very common abbreviation for Angular.js. As a front-end dev, at first glance motion-ng looks like an angular library. Whether that world is far enough from this is up to you to decide :)

**Comment by Mr-Dave** [comment]
The official motion application developer has agreed to transfer over the project which is a much better path forward than creating a entirely new project.  As a result, I am closing this issue and will be pursuing the necessary steps to move that forward.

**Comment by jeff-h** [comment]
Wow, great news! :)
