### ISSUE TITLE
Increment version to 3.4.1 and merge timelapse fix into 3.4 branch

### ISSUE THREAD

**Issue by tosiara** [Mr-Dave/motion#53]
Hi,
I would like to merge current "master" into 3.4 branch to include some fixes and especially the timelapse overwrite fix. And I think we should increment version to 3.4.1

If everyone agree I will do the job and create pull request for review

**Comment by Mr-Dave** [comment]
I am not going to be changing or doing anything with version numbers until there is something done with the official version.

**Comment by tosiara** [comment]
So in this case both official and unofficial will stale. I thought the main advantage of decentralized development was that things always keep going
