### ISSUE TITLE
vlc rtsp stream

### ISSUE THREAD

**Issue by jonathanbower** [Mr-Dave/motion#63]
Hi,
Just wondering if a rtsp stream from vlc is supposed to work in current master branch?

I'm streaming from an Raspberry Pi + camera module:
`cvlc v4l2:///dev/video0 --v4l2-width 640 --v4l2-height 480 --v4l2-chroma h264 --sout '#rtp{dst=0.0.0.0,port=8081,sdp=rtsp://10.10.1.91:8081/stream.sdp}'`

I can watch the stream in vlc, but motion gives me this error:
`[1] [ERR] [NET] netcam_rtsp_open_context: unable to open input(rtsp://10.10.1.91:8081/stream.sdp): Protocol not supported`

**Comment by tosiara** [comment]
AFAIK, vlc only supports UDP transport. So you need to set motion config to disable TCP transport

**Comment by jonathanbower** [comment]
Thank you! This solved it.
