### ISSUE TITLE
Detection of swscale headers

### ISSUE THREAD

**Issue by tosiara** [Mr-Dave/motion#76]
Would it be worth checking if swscale headers exist during config?
RTSP requires swscale and assumes it exists as soon as ffmpeg is detected. But may fail compiling if it is missing:
```
configure:5330: checking for ffmpeg autodetecting libraries
configure:5358: result: found in /usr/lib/i386-linux-gnu
configure:5417: checking for ffmpeg headers in /usr
configure:5443: result: found /usr/include/libavformat/avformat.h
configure:5487: checking file_protocol is defined in ffmpeg ?
configure:5507: gcc -c -I/usr/include -DFFMPEG_NEW_INCLUDES -I/usr/include/libavformat  conftest.c >&5
```
compilation fails:
```
Version: Unofficial-Git-d71cebf
Platform: Linux (if this is incorrect, please read README.FreeBSD)

Generating dependencies, please wait...
netcam_rtsp.h:10:32: fatal error: libswscale/swscale.h: No such file or directory
compilation terminated.
netcam_rtsp.h:10:32: fatal error: libswscale/swscale.h: No such file or directory
compilation terminated.
make: *** [.depend] Error 1
```
`sudo apt-get install libswscale-dev` would resolve the issue in this case

**Comment by ntfs1984** [comment]
Unfortunately, this is not end.

gcc -g -O2 -D_REENTRANT -DHAVE_FFMPEG -I/usr/include -DFFMPEG_NEW_INCLUDES -DHAVE_FFMPEG_NEW -DMOTION_V4L2 -DMOTION_V4L2_OLD -DTYPE_32BIT="int" -DHAVE_BSWAP   -march=native -mtune=native -Wall -DVERSION=\"Unofficial-Git-d71cebf\" -Dsysconfdir=\"/usr/local/etc\"    -c -o ffmpeg.o ffmpeg.c
--------------------------------------------------------------------------------
Motion object files compiled.

Linking Motion...
--------------------------------------------------------------------------------
gcc -L/usr/lib/x86_64-linux-gnu -o motion motion.o logger.o conf.o draw.o jpegutils.o vloopback_motion.o video.o video2.o video_common.o netcam.o netcam_ftp.o netcam_jpeg.o netcam_wget.o track.o alg.o event.o picture.o rotate.o webhttpd.o stream.o md5.o netcam_rtsp.o ffmpeg.o  -lm  -lpthread -ljpeg -L/usr/lib/x86_64-linux-gnu  -lavformat -lavcodec -lavutil -lm -lz -lswscale  
/usr/bin/ld: cannot find -lz
/usr/bin/ld: cannot find -lswscale
collect2: error: ld returned 1 exit status
make: *** [motion] Error 1

- - -
Ubuntu 14.04

**Comment by Mr-Dave** [comment]
I think that the next step with this is to really take a fresh look at that whole configure.ac and the interaction with the flags in the code.  I think it is way too messy in there.  Do we really need three ffmpeg flags?  Are the directories being interrogated even the correct ones with the latest distros?  Do we even have documentation of all the config options that currently exist?  etc.  

What I'd like to do is keep this issue open until that complete evaluation of the configure.ac has been completed and vetted with the maintainer.  Personally, I think that some of the default configure options need to change but that is a maintainer decision to make.  (e.g. Make ffmpeg default to required and a configure option to exclude)

**Comment by Mr-Dave** [comment]
Proposed change is on unstable branch

**Comment by Mr-Dave** [comment]
Revision in the unstable branch.  Re-open if any issue is found
