### ISSUE TITLE
various configure errors

### ISSUE THREAD

**Issue by ccrisan** [Mr-Dave/motion#90]
I recently decided to update the motion-mrdave package in [motionEyeOS](https://github.com/ccrisan/motioneyeos) to the latest commit and I stumbled upon some weird ./configure errors.

After running `autoconf` I got a `./configure` script that has a bit of an invalid syntax:

    ./configure: line 5283: `	PKG_CHECK_MODULES(FFMPEG, libavutil libavformat libavcodec libswscale, HAVE_FFMPEG=yes)'

I commented it out assuming it's just some autoconf parsing error and then I got the following error:

    `config.status: error: cannot find input file: `config.h.in'`

I feel like I'm missing something obvious here as I tried to go back a few commits (many actually) and the configure script still fails.

**Comment by ccrisan** [comment]
Nevermind, it turns out I need to use `autoreconf` instead of `autoconf`.

**Comment by tosiara** [comment]
You could also check for the solution in this report: https://github.com/Mr-Dave/motion/issues/85
