### ISSUE TITLE
/etc/init.d/motion : unreconized service (/etc/init.d/motion not created? )

### ISSUE THREAD

**Issue by Adamanusia** [Mr-Dave/motion#91]
First i am newbie,so bear with me :)

This is my first time compiling motion with your sources,since official motion binary (i am using raspbian)
didnt come with mp4 ffmpeg output support.

compiling,installing even running seems fine
.mp4 was produced

but why,with daemon seting turned on
i cant start motion by typing : 
service motion start
or
/etc/init.d/motion start

it always produce /etc/init.d/motion : unreconized service

turned out, /etc/init.d/motion is not created at all
moreover,motion user is not created too

is this normal if u compile motion from source?

Thank you for your support
sorry if this question sound sily and newbish

**Comment by tosiara** [comment]
You need to provide complete log of all the steps you have taken. Open a shell, perform all from scratch and copy shell contents here

**Comment by Adamanusia** [comment]
I just followed this tutorial:
https://tyrolite.wordpress.com/2015/03/07/building-motion-with-ffmpeg-and-rtsp-support/

but,i can reproduce it by uninstalling and reinstalling it:
here is script terminal log during compilation:
http://pastebin.com/F7pB4v76

here is my motion.conf
http://pastebin.com/70Y87y89


after seen this again,i notice after compilation,it said:

"More configuration examples as well as init scripts
can be found in /usr/local/share/motion/examples."

and in that folder ,there is init script for motion
but,why its so different than in:
http://www.lavrsen.dk/foswiki/pub/Motion/FrequentlyAskedQuestions/motion

so,iif i compile motion from source,that mean it will not produce init file automatically?

thank you very much for your answer

**Comment by tosiara** [comment]
Service creation/registration depends on the system. So this may need to be asked in appropriate group
From you lg compilation went fine and you should have "motion" binary in the source directory. Just run it from there using following command: ./motion -c /path/to/your/motion.cinf

**Comment by Adamanusia** [comment]
I see

eventually i have managed creating init.d script,but it gives me 
vid_v4lx_start: Failed to open video device /dev/video0: Permission denied

but that another story/issue

anyway

thank you very much for answering and clearing this
i think i will close this issue
