### ISSUE TITLE
Has ffmpeg_deinterlace been dropped?

### ISSUE THREAD

**Issue by tosiara** [Mr-Dave/motion#96]
I have built `Motion Unofficial-Git-2caced3` and noticed this warning:
```
conf_cmdparse: Unknown config option "ffmpeg_deinterlace"
```
Does it mean motion no longer able to do deinterlace? Or is it my `ffmpeg`'s fault?

**Comment by Mr-Dave** [comment]
Yes Motion is no longer able to do deinterlace.  Yes, FFMPEG depreciated the option which led to its removal.  The recommendation from the ffmpeg team was to use "filters" but until recently, I had not seen samples of how to accomplish it.

**Comment by tosiara** [comment]
Fair enough. Have we mentioned the deprecation in docs or change log?

**Comment by Mr-Dave** [comment]
It was removed way back when ffmpeg was re-written and should be in the change log.  I know it is in the document that describes the changed options that is in the wiki patch page.

**Comment by tosiara** [comment]
Ok, thanks!
